---
- name: Install Nginx
  apt:
    name=nginx
    state=latest
- name: copy the nginx config file
  copy:
    src: files/nginx
    dest: /etc/nginx/sites-enabled/default
  become: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
- name: nginx status
  shell: systemctl status nginx