---
- name: Install Nginx
  apt:
    name=nginx
    state=latest
- name: copy the nginx config file
  become: yes
  templates:
    src: "{{ item }}.j2"
    dest: /etc/nginx/sites-enabled/default
  with_items:
    - nginx
- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
- name: nginx status
  shell: systemctl status nginx