---
- name: add user ans
  vars_files:
    - inventory/local/group_vars/all.yml
  hosts: localhost
  become: yes
  roles:
    - role: create_user

- name: roles create file application.json
  hosts: localhost
  roles:
    - role: create_file

- name: install Nginx
  vars_files:
    - inventory/local/group_vars/all.yml
  hosts: localhost
  become: yes
  roles:
    - role: nginx

- name: roles Create folder
  hosts: localhost
  become: yes
  roles:
    - role: create_folder

- name: roles Download pic
  hosts: localhost
  become: yes
  roles:
    - role: download

- name: Test localhost
  hosts: localhost
  tasks:
    - shell: echo "123"