---
- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  ansible.builtin.user:
    name: james
    shell: /bin/bash
    groups: admins,developers
    append: yes

- name: Test localhost
  hosts: localhost
  tasks:
    - shell: echo "123"

- name: roles create file
  hosts: localhost
  roles:
    - role: create_file

- name: roles from infra
  hosts: localhost
  roles:
    - role: infra/restart_services